"""One-time patch for HTML pages that are NOT regenerated by build_site.py.

Applies the same E-E-A-T + schema framework to legacy pages produced by
build_search_console_expansion.py:

- Inject hardcoded JSON-LD <script> in <head> (replacing the JS-injected schemas
  that no longer fire because main.js dropped injectSchema()).
- Replace the "Editorial Team" byline block with the Javi Pérez byline.
- Update "2025 to 2026" / "in 2025 and 2026" copy in titles, h1s, descriptions.
- Update "Last reviewed: April 2026" -> "Last reviewed: May 2026".
- Drop the now-unused data-breadcrumbs / data-faqs body attributes.

Run from the repo root: python3 scripts/patch_orphan_pages.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

import build_site as bs  # noqa: E402

ORPHANS = [
    "pages/balance-transfer-credit-cards.html",
    "pages/checking-account-fees-guide.html",
    "pages/credit-card-annual-fees-guide.html",
    "pages/credit-card-interest-rates-explained.html",
    "pages/credit-score-for-car-loan.html",
    "pages/credit-score-for-mortgage.html",
    "pages/credit-score-improvement-plan.html",
    "pages/credit-score-ranges-guide.html",
    "pages/debt-consolidation-loan-guide.html",
    "pages/does-budgeting-help-credit-score.html",
    "pages/first-time-buyer-credit-guide.html",
    "pages/how-credit-utilization-affects-score.html",
    "pages/how-much-does-credit-score-cost.html",
    "pages/how-to-compare-credit-cards.html",
    "pages/how-to-get-approved-personal-loan.html",
    "pages/how-to-raise-credit-score.html",
    "pages/personal-loan-cost-guide.html",
    "pages/savings-account-interest-rates.html",
    "pages/smartcredit-review.html",
]


YEAR_FIXES = [
    (re.compile(r"\b2025 to 2026\b"), "2026"),
    (re.compile(r"\bin 2025 and 2026\b"), "in 2026"),
    (re.compile(r"\b2024 to 2026\b"), "2026"),
]


def _title_from_path(slug_path: str) -> str:
    return bs.title_from_path(slug_path)


def _extract(text: str, pattern: str, flags: int = 0, group: int = 1) -> str | None:
    m = re.search(pattern, text, flags)
    return m.group(group) if m else None


def patch_one(rel_path: str) -> None:
    abs_path = ROOT / rel_path
    src = abs_path.read_text(encoding="utf-8")
    original = src

    # Year fixes (titles, h1, body copy).
    for pat, repl in YEAR_FIXES:
        src = pat.sub(repl, src)

    # Keep editor photo path in sync with build_site.py if it drifted.
    src = src.replace(
        f"{bs.DOMAIN}/assets/images/javi-perez.jpg",
        bs.EDITOR_PHOTO,
    )

    # Drop body-level dataset attributes that fed the now-removed JS schema.
    src = re.sub(
        r"(\s+data-breadcrumbs=\"[^\"]*\")|(\s+data-faqs=\"[^\"]*\")",
        "",
        src,
    )

    # Replace any "Editorial Team" / "Last reviewed: April 2026" block.
    src = re.sub(
        r"<div class=\"editorial-block\">.*?</div>",
        "",
        src,
        flags=re.DOTALL,
    )

    title = _extract(src, r"<title>(.*?)</title>") or _title_from_path(rel_path)
    description = _extract(src, r'<meta name="description" content="(.*?)"') or title
    canonical = (
        _extract(src, r'<link rel="canonical" href="(.*?)"')
        or bs.url_for(rel_path)
    )

    breadcrumbs = [
        {"name": "Home", "url": f"{bs.DOMAIN}/"},
        {"name": "Guides", "url": f"{bs.DOMAIN}/pages/personal-loans-guide"},
        {"name": title, "url": canonical},
    ]

    schema_payload = bs.build_jsonld(
        path=rel_path,
        title=title,
        description=description,
        page_type="article",
        breadcrumbs=breadcrumbs,
        faqs=None,
    )
    schema_tag = (
        f'<script type="application/ld+json">{schema_payload}</script>'
    )

    if "application/ld+json" not in src:
        src = src.replace(
            "</head>",
            f"          {schema_tag}\n        </head>",
            1,
        )

    if 'class="editorial-byline"' not in src and 'class="ccg-author-box editorial-byline"' not in src:
        byline = bs.author_box().rstrip()
        src = src.replace("</main>", f"{byline}\n</main>", 1)

    if src != original:
        abs_path.write_text(src, encoding="utf-8")
        print(f"patched: {rel_path}")
    else:
        print(f"no change: {rel_path}")


def main() -> None:
    for path in ORPHANS:
        patch_one(path)


if __name__ == "__main__":
    main()
